### ISSUE TITLE
Нарушена семантика

### ISSUE THREAD

**Issue by aleksandrmamzikov** [rr-cosmonaut/EcoSwap#3]
https://github.com/rr-cosmonaut/EcoSwap/blob/afca7a2902be8951c512c11f2d8c7912d5ce0f31/index.html#L60

Не семантический выбор html тегов для верстки. Для заголовков необходимо использовать теги `h1-h6`, для текстовых параграфов `p` и т.д. У тебя практически все на `div`. Почитай краткую статью по теме https://habr.com/ru/companies/htmlacademy/articles/546500/

**Comment by rr-cosmonaut** [comment]
https://github.com/rr-cosmonaut/EcoSwap/pull/14

**Comment by rr-cosmonaut** [comment]
https://github.com/rr-cosmonaut/EcoSwap/pull/14
