### ISSUE TITLE
Огромные отступы

### ISSUE THREAD

**Issue by aleksandrmamzikov** [rr-cosmonaut/EcoSwap#5]
https://github.com/rr-cosmonaut/EcoSwap/blob/afca7a2902be8951c512c11f2d8c7912d5ce0f31/css/styles.css#L188

https://github.com/rr-cosmonaut/EcoSwap/blob/afca7a2902be8951c512c11f2d8c7912d5ce0f31/css/styles.css#L182

Если проходится задавать такие огромные отступы, значит что то не так в верстке. Это плохая практика, страница становится плохо адаптируемой. Есть другие способы

**Comment by rr-cosmonaut** [comment]
Поправил

**Comment by aleksandrmamzikov** [comment]
где поправил?

**Comment by rr-cosmonaut** [comment]
https://github.com/rr-cosmonaut/EcoSwap/commit/df896075bd26d9c5736fe4c0c5d51428ff418df5
